name = "DiffEqProblemLibrary"
uuid = "a077e3f3-b75c-5d7f-a0c6-6bc4c8ec64a9"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "4.5.0"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqBiological = "eb300fae-53e8-50a0-950c-e21f52c2b7e0"
DiffEqOperators = "9fdde737-9c7f-55bf-ade8-46b3f136cc48"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
DiffEqBase = ">= 5.15.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
